/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VinculacaoRouteImport } from './routes/vinculacao'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RemetentesRouteImport } from './routes/remetentes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricosRouteImport } from './routes/historicos'
import { Route as GestaoFrotaRouteImport } from './routes/gestao-frota'
import { Route as DestinatariosRouteImport } from './routes/destinatarios'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CarretasRouteImport } from './routes/carretas'
import { Route as AbastecimentosRouteImport } from './routes/abastecimentos'
import { Route as IndexRouteImport } from './routes/index'

const VinculacaoRoute = VinculacaoRouteImport.update({
  id: '/vinculacao',
  path: '/vinculacao',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RemetentesRoute = RemetentesRouteImport.update({
  id: '/remetentes',
  path: '/remetentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricosRoute = HistoricosRouteImport.update({
  id: '/historicos',
  path: '/historicos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoFrotaRoute = GestaoFrotaRouteImport.update({
  id: '/gestao-frota',
  path: '/gestao-frota',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinatariosRoute = DestinatariosRouteImport.update({
  id: '/destinatarios',
  path: '/destinatarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarretasRoute = CarretasRouteImport.update({
  id: '/carretas',
  path: '/carretas',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecimentosRoute = AbastecimentosRouteImport.update({
  id: '/abastecimentos',
  path: '/abastecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/carretas': typeof CarretasRoute
  '/clientes': typeof ClientesRoute
  '/destinatarios': typeof DestinatariosRoute
  '/gestao-frota': typeof GestaoFrotaRoute
  '/historicos': typeof HistoricosRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/remetentes': typeof RemetentesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/vinculacao': typeof VinculacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/carretas': typeof CarretasRoute
  '/clientes': typeof ClientesRoute
  '/destinatarios': typeof DestinatariosRoute
  '/gestao-frota': typeof GestaoFrotaRoute
  '/historicos': typeof HistoricosRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/remetentes': typeof RemetentesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/vinculacao': typeof VinculacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/carretas': typeof CarretasRoute
  '/clientes': typeof ClientesRoute
  '/destinatarios': typeof DestinatariosRoute
  '/gestao-frota': typeof GestaoFrotaRoute
  '/historicos': typeof HistoricosRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/remetentes': typeof RemetentesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/vinculacao': typeof VinculacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abastecimentos'
    | '/carretas'
    | '/clientes'
    | '/destinatarios'
    | '/gestao-frota'
    | '/historicos'
    | '/login'
    | '/mapa'
    | '/motoristas'
    | '/produtos'
    | '/remetentes'
    | '/usuarios'
    | '/veiculos'
    | '/vinculacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abastecimentos'
    | '/carretas'
    | '/clientes'
    | '/destinatarios'
    | '/gestao-frota'
    | '/historicos'
    | '/login'
    | '/mapa'
    | '/motoristas'
    | '/produtos'
    | '/remetentes'
    | '/usuarios'
    | '/veiculos'
    | '/vinculacao'
  id:
    | '__root__'
    | '/'
    | '/abastecimentos'
    | '/carretas'
    | '/clientes'
    | '/destinatarios'
    | '/gestao-frota'
    | '/historicos'
    | '/login'
    | '/mapa'
    | '/motoristas'
    | '/produtos'
    | '/remetentes'
    | '/usuarios'
    | '/veiculos'
    | '/vinculacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbastecimentosRoute: typeof AbastecimentosRoute
  CarretasRoute: typeof CarretasRoute
  ClientesRoute: typeof ClientesRoute
  DestinatariosRoute: typeof DestinatariosRoute
  GestaoFrotaRoute: typeof GestaoFrotaRoute
  HistoricosRoute: typeof HistoricosRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MotoristasRoute: typeof MotoristasRoute
  ProdutosRoute: typeof ProdutosRoute
  RemetentesRoute: typeof RemetentesRoute
  UsuariosRoute: typeof UsuariosRoute
  VeiculosRoute: typeof VeiculosRoute
  VinculacaoRoute: typeof VinculacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vinculacao': {
      id: '/vinculacao'
      path: '/vinculacao'
      fullPath: '/vinculacao'
      preLoaderRoute: typeof VinculacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remetentes': {
      id: '/remetentes'
      path: '/remetentes'
      fullPath: '/remetentes'
      preLoaderRoute: typeof RemetentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historicos': {
      id: '/historicos'
      path: '/historicos'
      fullPath: '/historicos'
      preLoaderRoute: typeof HistoricosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-frota': {
      id: '/gestao-frota'
      path: '/gestao-frota'
      fullPath: '/gestao-frota'
      preLoaderRoute: typeof GestaoFrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinatarios': {
      id: '/destinatarios'
      path: '/destinatarios'
      fullPath: '/destinatarios'
      preLoaderRoute: typeof DestinatariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carretas': {
      id: '/carretas'
      path: '/carretas'
      fullPath: '/carretas'
      preLoaderRoute: typeof CarretasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecimentos': {
      id: '/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/abastecimentos'
      preLoaderRoute: typeof AbastecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbastecimentosRoute: AbastecimentosRoute,
  CarretasRoute: CarretasRoute,
  ClientesRoute: ClientesRoute,
  DestinatariosRoute: DestinatariosRoute,
  GestaoFrotaRoute: GestaoFrotaRoute,
  HistoricosRoute: HistoricosRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MotoristasRoute: MotoristasRoute,
  ProdutosRoute: ProdutosRoute,
  RemetentesRoute: RemetentesRoute,
  UsuariosRoute: UsuariosRoute,
  VeiculosRoute: VeiculosRoute,
  VinculacaoRoute: VinculacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
