/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VinculacaoRouteImport } from './routes/vinculacao'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RemetentesRouteImport } from './routes/remetentes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LucrosDespesasRouteImport } from './routes/lucros-despesas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricosRouteImport } from './routes/historicos'
import { Route as GestaoFrotaRouteImport } from './routes/gestao-frota'
import { Route as FrotakIaRouteImport } from './routes/frotak-ia'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DestinatariosRouteImport } from './routes/destinatarios'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CarretasRouteImport } from './routes/carretas'
import { Route as AbastecimentosRouteImport } from './routes/abastecimentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceiroSalariosRouteImport } from './routes/financeiro.salarios'
import { Route as FinanceiroRentabilidadeRouteImport } from './routes/financeiro.rentabilidade'
import { Route as FinanceiroRecorrenciasRouteImport } from './routes/financeiro.recorrencias'
import { Route as FinanceiroReceberRouteImport } from './routes/financeiro.receber'
import { Route as FinanceiroPlanoContasRouteImport } from './routes/financeiro.plano-contas'
import { Route as FinanceiroPagarRouteImport } from './routes/financeiro.pagar'
import { Route as FinanceiroIntegracoesRouteImport } from './routes/financeiro.integracoes'
import { Route as FinanceiroFluxoCaixaRouteImport } from './routes/financeiro.fluxo-caixa'
import { Route as FinanceiroDreRouteImport } from './routes/financeiro.dre'
import { Route as FinanceiroContasRouteImport } from './routes/financeiro.contas'
import { Route as FinanceiroCentrosCustoRouteImport } from './routes/financeiro.centros-custo'
import { Route as ApiSascarSyncRouteImport } from './routes/api/sascar/sync'

const VinculacaoRoute = VinculacaoRouteImport.update({
  id: '/vinculacao',
  path: '/vinculacao',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RemetentesRoute = RemetentesRouteImport.update({
  id: '/remetentes',
  path: '/remetentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LucrosDespesasRoute = LucrosDespesasRouteImport.update({
  id: '/lucros-despesas',
  path: '/lucros-despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricosRoute = HistoricosRouteImport.update({
  id: '/historicos',
  path: '/historicos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoFrotaRoute = GestaoFrotaRouteImport.update({
  id: '/gestao-frota',
  path: '/gestao-frota',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotakIaRoute = FrotakIaRouteImport.update({
  id: '/frotak-ia',
  path: '/frotak-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinatariosRoute = DestinatariosRouteImport.update({
  id: '/destinatarios',
  path: '/destinatarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarretasRoute = CarretasRouteImport.update({
  id: '/carretas',
  path: '/carretas',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecimentosRoute = AbastecimentosRouteImport.update({
  id: '/abastecimentos',
  path: '/abastecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroSalariosRoute = FinanceiroSalariosRouteImport.update({
  id: '/salarios',
  path: '/salarios',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroRentabilidadeRoute = FinanceiroRentabilidadeRouteImport.update({
  id: '/rentabilidade',
  path: '/rentabilidade',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroRecorrenciasRoute = FinanceiroRecorrenciasRouteImport.update({
  id: '/recorrencias',
  path: '/recorrencias',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroReceberRoute = FinanceiroReceberRouteImport.update({
  id: '/receber',
  path: '/receber',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroPlanoContasRoute = FinanceiroPlanoContasRouteImport.update({
  id: '/plano-contas',
  path: '/plano-contas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroPagarRoute = FinanceiroPagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroIntegracoesRoute = FinanceiroIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroFluxoCaixaRoute = FinanceiroFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroDreRoute = FinanceiroDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroContasRoute = FinanceiroContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroCentrosCustoRoute = FinanceiroCentrosCustoRouteImport.update({
  id: '/centros-custo',
  path: '/centros-custo',
  getParentRoute: () => FinanceiroRoute,
} as any)
const ApiSascarSyncRoute = ApiSascarSyncRouteImport.update({
  id: '/api/sascar/sync',
  path: '/api/sascar/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/carretas': typeof CarretasRoute
  '/clientes': typeof ClientesRoute
  '/destinatarios': typeof DestinatariosRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/frotak-ia': typeof FrotakIaRoute
  '/gestao-frota': typeof GestaoFrotaRoute
  '/historicos': typeof HistoricosRoute
  '/login': typeof LoginRoute
  '/lucros-despesas': typeof LucrosDespesasRoute
  '/mapa': typeof MapaRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/remetentes': typeof RemetentesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/vinculacao': typeof VinculacaoRoute
  '/financeiro/centros-custo': typeof FinanceiroCentrosCustoRoute
  '/financeiro/contas': typeof FinanceiroContasRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/integracoes': typeof FinanceiroIntegracoesRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/financeiro/recorrencias': typeof FinanceiroRecorrenciasRoute
  '/financeiro/rentabilidade': typeof FinanceiroRentabilidadeRoute
  '/financeiro/salarios': typeof FinanceiroSalariosRoute
  '/api/sascar/sync': typeof ApiSascarSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/carretas': typeof CarretasRoute
  '/clientes': typeof ClientesRoute
  '/destinatarios': typeof DestinatariosRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/frotak-ia': typeof FrotakIaRoute
  '/gestao-frota': typeof GestaoFrotaRoute
  '/historicos': typeof HistoricosRoute
  '/login': typeof LoginRoute
  '/lucros-despesas': typeof LucrosDespesasRoute
  '/mapa': typeof MapaRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/remetentes': typeof RemetentesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/vinculacao': typeof VinculacaoRoute
  '/financeiro/centros-custo': typeof FinanceiroCentrosCustoRoute
  '/financeiro/contas': typeof FinanceiroContasRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/integracoes': typeof FinanceiroIntegracoesRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/financeiro/recorrencias': typeof FinanceiroRecorrenciasRoute
  '/financeiro/rentabilidade': typeof FinanceiroRentabilidadeRoute
  '/financeiro/salarios': typeof FinanceiroSalariosRoute
  '/api/sascar/sync': typeof ApiSascarSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abastecimentos': typeof AbastecimentosRoute
  '/carretas': typeof CarretasRoute
  '/clientes': typeof ClientesRoute
  '/destinatarios': typeof DestinatariosRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/frotak-ia': typeof FrotakIaRoute
  '/gestao-frota': typeof GestaoFrotaRoute
  '/historicos': typeof HistoricosRoute
  '/login': typeof LoginRoute
  '/lucros-despesas': typeof LucrosDespesasRoute
  '/mapa': typeof MapaRoute
  '/motoristas': typeof MotoristasRoute
  '/produtos': typeof ProdutosRoute
  '/remetentes': typeof RemetentesRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/vinculacao': typeof VinculacaoRoute
  '/financeiro/centros-custo': typeof FinanceiroCentrosCustoRoute
  '/financeiro/contas': typeof FinanceiroContasRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/integracoes': typeof FinanceiroIntegracoesRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/plano-contas': typeof FinanceiroPlanoContasRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/financeiro/recorrencias': typeof FinanceiroRecorrenciasRoute
  '/financeiro/rentabilidade': typeof FinanceiroRentabilidadeRoute
  '/financeiro/salarios': typeof FinanceiroSalariosRoute
  '/api/sascar/sync': typeof ApiSascarSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abastecimentos'
    | '/carretas'
    | '/clientes'
    | '/destinatarios'
    | '/financeiro'
    | '/frotak-ia'
    | '/gestao-frota'
    | '/historicos'
    | '/login'
    | '/lucros-despesas'
    | '/mapa'
    | '/motoristas'
    | '/produtos'
    | '/remetentes'
    | '/usuarios'
    | '/veiculos'
    | '/vinculacao'
    | '/financeiro/centros-custo'
    | '/financeiro/contas'
    | '/financeiro/dre'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/integracoes'
    | '/financeiro/pagar'
    | '/financeiro/plano-contas'
    | '/financeiro/receber'
    | '/financeiro/recorrencias'
    | '/financeiro/rentabilidade'
    | '/financeiro/salarios'
    | '/api/sascar/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abastecimentos'
    | '/carretas'
    | '/clientes'
    | '/destinatarios'
    | '/financeiro'
    | '/frotak-ia'
    | '/gestao-frota'
    | '/historicos'
    | '/login'
    | '/lucros-despesas'
    | '/mapa'
    | '/motoristas'
    | '/produtos'
    | '/remetentes'
    | '/usuarios'
    | '/veiculos'
    | '/vinculacao'
    | '/financeiro/centros-custo'
    | '/financeiro/contas'
    | '/financeiro/dre'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/integracoes'
    | '/financeiro/pagar'
    | '/financeiro/plano-contas'
    | '/financeiro/receber'
    | '/financeiro/recorrencias'
    | '/financeiro/rentabilidade'
    | '/financeiro/salarios'
    | '/api/sascar/sync'
  id:
    | '__root__'
    | '/'
    | '/abastecimentos'
    | '/carretas'
    | '/clientes'
    | '/destinatarios'
    | '/financeiro'
    | '/frotak-ia'
    | '/gestao-frota'
    | '/historicos'
    | '/login'
    | '/lucros-despesas'
    | '/mapa'
    | '/motoristas'
    | '/produtos'
    | '/remetentes'
    | '/usuarios'
    | '/veiculos'
    | '/vinculacao'
    | '/financeiro/centros-custo'
    | '/financeiro/contas'
    | '/financeiro/dre'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/integracoes'
    | '/financeiro/pagar'
    | '/financeiro/plano-contas'
    | '/financeiro/receber'
    | '/financeiro/recorrencias'
    | '/financeiro/rentabilidade'
    | '/financeiro/salarios'
    | '/api/sascar/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbastecimentosRoute: typeof AbastecimentosRoute
  CarretasRoute: typeof CarretasRoute
  ClientesRoute: typeof ClientesRoute
  DestinatariosRoute: typeof DestinatariosRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  FrotakIaRoute: typeof FrotakIaRoute
  GestaoFrotaRoute: typeof GestaoFrotaRoute
  HistoricosRoute: typeof HistoricosRoute
  LoginRoute: typeof LoginRoute
  LucrosDespesasRoute: typeof LucrosDespesasRoute
  MapaRoute: typeof MapaRoute
  MotoristasRoute: typeof MotoristasRoute
  ProdutosRoute: typeof ProdutosRoute
  RemetentesRoute: typeof RemetentesRoute
  UsuariosRoute: typeof UsuariosRoute
  VeiculosRoute: typeof VeiculosRoute
  VinculacaoRoute: typeof VinculacaoRoute
  ApiSascarSyncRoute: typeof ApiSascarSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vinculacao': {
      id: '/vinculacao'
      path: '/vinculacao'
      fullPath: '/vinculacao'
      preLoaderRoute: typeof VinculacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remetentes': {
      id: '/remetentes'
      path: '/remetentes'
      fullPath: '/remetentes'
      preLoaderRoute: typeof RemetentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucros-despesas': {
      id: '/lucros-despesas'
      path: '/lucros-despesas'
      fullPath: '/lucros-despesas'
      preLoaderRoute: typeof LucrosDespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historicos': {
      id: '/historicos'
      path: '/historicos'
      fullPath: '/historicos'
      preLoaderRoute: typeof HistoricosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-frota': {
      id: '/gestao-frota'
      path: '/gestao-frota'
      fullPath: '/gestao-frota'
      preLoaderRoute: typeof GestaoFrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frotak-ia': {
      id: '/frotak-ia'
      path: '/frotak-ia'
      fullPath: '/frotak-ia'
      preLoaderRoute: typeof FrotakIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinatarios': {
      id: '/destinatarios'
      path: '/destinatarios'
      fullPath: '/destinatarios'
      preLoaderRoute: typeof DestinatariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carretas': {
      id: '/carretas'
      path: '/carretas'
      fullPath: '/carretas'
      preLoaderRoute: typeof CarretasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecimentos': {
      id: '/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/abastecimentos'
      preLoaderRoute: typeof AbastecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/salarios': {
      id: '/financeiro/salarios'
      path: '/salarios'
      fullPath: '/financeiro/salarios'
      preLoaderRoute: typeof FinanceiroSalariosRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/rentabilidade': {
      id: '/financeiro/rentabilidade'
      path: '/rentabilidade'
      fullPath: '/financeiro/rentabilidade'
      preLoaderRoute: typeof FinanceiroRentabilidadeRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/recorrencias': {
      id: '/financeiro/recorrencias'
      path: '/recorrencias'
      fullPath: '/financeiro/recorrencias'
      preLoaderRoute: typeof FinanceiroRecorrenciasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/receber': {
      id: '/financeiro/receber'
      path: '/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof FinanceiroReceberRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/plano-contas': {
      id: '/financeiro/plano-contas'
      path: '/plano-contas'
      fullPath: '/financeiro/plano-contas'
      preLoaderRoute: typeof FinanceiroPlanoContasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/pagar': {
      id: '/financeiro/pagar'
      path: '/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof FinanceiroPagarRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/integracoes': {
      id: '/financeiro/integracoes'
      path: '/integracoes'
      fullPath: '/financeiro/integracoes'
      preLoaderRoute: typeof FinanceiroIntegracoesRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/fluxo-caixa': {
      id: '/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof FinanceiroFluxoCaixaRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/dre': {
      id: '/financeiro/dre'
      path: '/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof FinanceiroDreRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/contas': {
      id: '/financeiro/contas'
      path: '/contas'
      fullPath: '/financeiro/contas'
      preLoaderRoute: typeof FinanceiroContasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/centros-custo': {
      id: '/financeiro/centros-custo'
      path: '/centros-custo'
      fullPath: '/financeiro/centros-custo'
      preLoaderRoute: typeof FinanceiroCentrosCustoRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/api/sascar/sync': {
      id: '/api/sascar/sync'
      path: '/api/sascar/sync'
      fullPath: '/api/sascar/sync'
      preLoaderRoute: typeof ApiSascarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceiroRouteChildren {
  FinanceiroCentrosCustoRoute: typeof FinanceiroCentrosCustoRoute
  FinanceiroContasRoute: typeof FinanceiroContasRoute
  FinanceiroDreRoute: typeof FinanceiroDreRoute
  FinanceiroFluxoCaixaRoute: typeof FinanceiroFluxoCaixaRoute
  FinanceiroIntegracoesRoute: typeof FinanceiroIntegracoesRoute
  FinanceiroPagarRoute: typeof FinanceiroPagarRoute
  FinanceiroPlanoContasRoute: typeof FinanceiroPlanoContasRoute
  FinanceiroReceberRoute: typeof FinanceiroReceberRoute
  FinanceiroRecorrenciasRoute: typeof FinanceiroRecorrenciasRoute
  FinanceiroRentabilidadeRoute: typeof FinanceiroRentabilidadeRoute
  FinanceiroSalariosRoute: typeof FinanceiroSalariosRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroCentrosCustoRoute: FinanceiroCentrosCustoRoute,
  FinanceiroContasRoute: FinanceiroContasRoute,
  FinanceiroDreRoute: FinanceiroDreRoute,
  FinanceiroFluxoCaixaRoute: FinanceiroFluxoCaixaRoute,
  FinanceiroIntegracoesRoute: FinanceiroIntegracoesRoute,
  FinanceiroPagarRoute: FinanceiroPagarRoute,
  FinanceiroPlanoContasRoute: FinanceiroPlanoContasRoute,
  FinanceiroReceberRoute: FinanceiroReceberRoute,
  FinanceiroRecorrenciasRoute: FinanceiroRecorrenciasRoute,
  FinanceiroRentabilidadeRoute: FinanceiroRentabilidadeRoute,
  FinanceiroSalariosRoute: FinanceiroSalariosRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbastecimentosRoute: AbastecimentosRoute,
  CarretasRoute: CarretasRoute,
  ClientesRoute: ClientesRoute,
  DestinatariosRoute: DestinatariosRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  FrotakIaRoute: FrotakIaRoute,
  GestaoFrotaRoute: GestaoFrotaRoute,
  HistoricosRoute: HistoricosRoute,
  LoginRoute: LoginRoute,
  LucrosDespesasRoute: LucrosDespesasRoute,
  MapaRoute: MapaRoute,
  MotoristasRoute: MotoristasRoute,
  ProdutosRoute: ProdutosRoute,
  RemetentesRoute: RemetentesRoute,
  UsuariosRoute: UsuariosRoute,
  VeiculosRoute: VeiculosRoute,
  VinculacaoRoute: VinculacaoRoute,
  ApiSascarSyncRoute: ApiSascarSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
