/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as BiRouteImport } from './routes/bi'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FuncoesRouteImport } from './routes/funcoes'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as OperacoesRouteImport } from './routes/operacoes'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as AcademyModuleRouteImport } from './routes/academy.$module'
import { Route as BiModuleRouteImport } from './routes/bi.$module'
import { Route as DevelopersModuleRouteImport } from './routes/developers.$module'
import { Route as PartnersModuleRouteImport } from './routes/partners.$module'
import { Route as SandboxModuleRouteImport } from './routes/sandbox.$module'
import { Route as StatusModuleRouteImport } from './routes/status.$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncoesRoute = FuncoesRouteImport.update({
  id: '/funcoes',
  path: '/funcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRoute = OperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyModuleRoute = AcademyModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AcademyRoute,
} as any)
const BiModuleRoute = BiModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => BiRoute,
} as any)
const DevelopersModuleRoute = DevelopersModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => DevelopersRoute,
} as any)
const PartnersModuleRoute = PartnersModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => PartnersRoute,
} as any)
const SandboxModuleRoute = SandboxModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => SandboxRoute,
} as any)
const StatusModuleRoute = StatusModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => StatusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/bi': typeof BiRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/funcoes': typeof FuncoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/operacoes': typeof OperacoesRoute
  '/partners': typeof PartnersRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/permissoes': typeof PermissoesRoute
  '/sandbox': typeof SandboxRouteWithChildren
  '/status': typeof StatusRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/webhooks': typeof WebhooksRoute
  '/academy/$module': typeof AcademyModuleRoute
  '/bi/$module': typeof BiModuleRoute
  '/developers/$module': typeof DevelopersModuleRoute
  '/partners/$module': typeof PartnersModuleRoute
  '/sandbox/$module': typeof SandboxModuleRoute
  '/status/$module': typeof StatusModuleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/bi': typeof BiRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/funcoes': typeof FuncoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/operacoes': typeof OperacoesRoute
  '/partners': typeof PartnersRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/permissoes': typeof PermissoesRoute
  '/sandbox': typeof SandboxRouteWithChildren
  '/status': typeof StatusRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/webhooks': typeof WebhooksRoute
  '/academy/$module': typeof AcademyModuleRoute
  '/bi/$module': typeof BiModuleRoute
  '/developers/$module': typeof DevelopersModuleRoute
  '/partners/$module': typeof PartnersModuleRoute
  '/sandbox/$module': typeof SandboxModuleRoute
  '/status/$module': typeof StatusModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/bi': typeof BiRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/developers': typeof DevelopersRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/funcoes': typeof FuncoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/operacoes': typeof OperacoesRoute
  '/partners': typeof PartnersRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/permissoes': typeof PermissoesRoute
  '/sandbox': typeof SandboxRouteWithChildren
  '/status': typeof StatusRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/webhooks': typeof WebhooksRoute
  '/academy/$module': typeof AcademyModuleRoute
  '/bi/$module': typeof BiModuleRoute
  '/developers/$module': typeof DevelopersModuleRoute
  '/partners/$module': typeof PartnersModuleRoute
  '/sandbox/$module': typeof SandboxModuleRoute
  '/status/$module': typeof StatusModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/alertas'
    | '/auditoria'
    | '/bi'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/developers'
    | '/financeiro'
    | '/funcoes'
    | '/integracoes'
    | '/login'
    | '/mapa'
    | '/monitoramento'
    | '/operacoes'
    | '/partners'
    | '/perfil'
    | '/permissoes'
    | '/sandbox'
    | '/status'
    | '/suporte'
    | '/usuarios'
    | '/webhooks'
    | '/academy/$module'
    | '/bi/$module'
    | '/developers/$module'
    | '/partners/$module'
    | '/sandbox/$module'
    | '/status/$module'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/alertas'
    | '/auditoria'
    | '/bi'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/developers'
    | '/financeiro'
    | '/funcoes'
    | '/integracoes'
    | '/login'
    | '/mapa'
    | '/monitoramento'
    | '/operacoes'
    | '/partners'
    | '/perfil'
    | '/permissoes'
    | '/sandbox'
    | '/status'
    | '/suporte'
    | '/usuarios'
    | '/webhooks'
    | '/academy/$module'
    | '/bi/$module'
    | '/developers/$module'
    | '/partners/$module'
    | '/sandbox/$module'
    | '/status/$module'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/alertas'
    | '/auditoria'
    | '/bi'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/developers'
    | '/financeiro'
    | '/funcoes'
    | '/integracoes'
    | '/login'
    | '/mapa'
    | '/monitoramento'
    | '/operacoes'
    | '/partners'
    | '/perfil'
    | '/permissoes'
    | '/sandbox'
    | '/status'
    | '/suporte'
    | '/usuarios'
    | '/webhooks'
    | '/academy/$module'
    | '/bi/$module'
    | '/developers/$module'
    | '/partners/$module'
    | '/sandbox/$module'
    | '/status/$module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AlertasRoute: typeof AlertasRoute
  AuditoriaRoute: typeof AuditoriaRoute
  BiRoute: typeof BiRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  ComercialRoute: typeof ComercialRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DevelopersRoute: typeof DevelopersRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
  FuncoesRoute: typeof FuncoesRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  OperacoesRoute: typeof OperacoesRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  PermissoesRoute: typeof PermissoesRoute
  SandboxRoute: typeof SandboxRouteWithChildren
  StatusRoute: typeof StatusRouteWithChildren
  SuporteRoute: typeof SuporteRoute
  UsuariosRoute: typeof UsuariosRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcoes': {
      id: '/funcoes'
      path: '/funcoes'
      fullPath: '/funcoes'
      preLoaderRoute: typeof FuncoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes': {
      id: '/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof OperacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$module': {
      id: '/academy/$module'
      path: '/$module'
      fullPath: '/academy/$module'
      preLoaderRoute: typeof AcademyModuleRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/bi/$module': {
      id: '/bi/$module'
      path: '/$module'
      fullPath: '/bi/$module'
      preLoaderRoute: typeof BiModuleRouteImport
      parentRoute: typeof BiRoute
    }
    '/developers/$module': {
      id: '/developers/$module'
      path: '/$module'
      fullPath: '/developers/$module'
      preLoaderRoute: typeof DevelopersModuleRouteImport
      parentRoute: typeof DevelopersRoute
    }
    '/partners/$module': {
      id: '/partners/$module'
      path: '/$module'
      fullPath: '/partners/$module'
      preLoaderRoute: typeof PartnersModuleRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/sandbox/$module': {
      id: '/sandbox/$module'
      path: '/$module'
      fullPath: '/sandbox/$module'
      preLoaderRoute: typeof SandboxModuleRouteImport
      parentRoute: typeof SandboxRoute
    }
    '/status/$module': {
      id: '/status/$module'
      path: '/$module'
      fullPath: '/status/$module'
      preLoaderRoute: typeof StatusModuleRouteImport
      parentRoute: typeof StatusRoute
    }
  }
}

interface AcademyRouteChildren {
  AcademyModuleRoute: typeof AcademyModuleRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyModuleRoute: AcademyModuleRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface BiRouteChildren {
  BiModuleRoute: typeof BiModuleRoute
}

const BiRouteChildren: BiRouteChildren = {
  BiModuleRoute: BiModuleRoute,
}

const BiRouteWithChildren = BiRoute._addFileChildren(BiRouteChildren)

interface DevelopersRouteChildren {
  DevelopersModuleRoute: typeof DevelopersModuleRoute
}

const DevelopersRouteChildren: DevelopersRouteChildren = {
  DevelopersModuleRoute: DevelopersModuleRoute,
}

const DevelopersRouteWithChildren = DevelopersRoute._addFileChildren(
  DevelopersRouteChildren,
)

interface PartnersRouteChildren {
  PartnersModuleRoute: typeof PartnersModuleRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersModuleRoute: PartnersModuleRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

interface SandboxRouteChildren {
  SandboxModuleRoute: typeof SandboxModuleRoute
}

const SandboxRouteChildren: SandboxRouteChildren = {
  SandboxModuleRoute: SandboxModuleRoute,
}

const SandboxRouteWithChildren =
  SandboxRoute._addFileChildren(SandboxRouteChildren)

interface StatusRouteChildren {
  StatusModuleRoute: typeof StatusModuleRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusModuleRoute: StatusModuleRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AlertasRoute: AlertasRoute,
  AuditoriaRoute: AuditoriaRoute,
  BiRoute: BiRouteWithChildren,
  ClientesRoute: ClientesRoute,
  ComercialRoute: ComercialRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DevelopersRoute: DevelopersRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
  FuncoesRoute: FuncoesRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  OperacoesRoute: OperacoesRoute,
  PartnersRoute: PartnersRouteWithChildren,
  PerfilRoute: PerfilRoute,
  PermissoesRoute: PermissoesRoute,
  SandboxRoute: SandboxRouteWithChildren,
  StatusRoute: StatusRouteWithChildren,
  SuporteRoute: SuporteRoute,
  UsuariosRoute: UsuariosRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
